name: Daily Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 00:00 UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "Shubham Bot"
          git config user.email "your-email@example.com"

      - name: Update dummy file
        run: |
          echo "Auto-update: $(date)" >> dummy.txt

      - name: Commit and Push
        run: |
          git add .
          git commit -m "🤖 Auto commit $(date)"
          git push
